### PR TITLE
Numerics port

### PR DESCRIPTION
**Pull request by mconcat**
## Description

Add 64.64 fixed point arithmetic to Shoshin. Code is ported from [cubit](https://github.com/influenceth/cubit). 

## Approach

Port basic arithmetic code from cubit, including + - * / %, and corresponding test code.

## Tasks left

- [x] Make all unit test work
- [ ] Import randomize testing
- [ ] Write few more helper functions

### CODE REVIEW

**Comment by mconcat** [comment]
Test failing due to https://github.com/starkware-libs/cairo/issues/2808

**Comment by guiltygyoza** [comment]
> Test failing due to [starkware-libs/cairo#2808](https://github.com/starkware-libs/cairo/issues/2808)

what happened to the failed test due to this bug?

**Comment by guiltygyoza** [comment]
> * [ ]  Write few more helper functions

Could you elaborate what these helper functions do?

**Comment by mconcat** [comment]
The widemul extern function made out of range error when given a u128 argument out of u64 max. This error is fixed and merged in the main branch of cairo

**Pull request merged**
